export const cast = [
  {
    id: "antonyStarr",
    name: "Antony Starr",
    knownAs: "actor",
    nationality: "New Zealand",
    bio: "Antony Starr is a New Zealand actor known for his role as Homelander in the TV series 'The Boys.' With his compelling portrayal of the complex character, Starr has captivated audiences and showcased his exceptional acting abilities. Prior to 'The Boys,' he gained recognition for his performance in the TV series 'Banshee,' where he portrayed the protagonist with intensity and depth.",
  },
  {
    id: "jackGylenhaal",
    name: "Jake Gyllenhaal",
    knownAs: "actor",
    nationality: "United States",
    bio: "Jake Gyllenhaal is an American actor known for his versatile roles in films such as 'Brokeback Mountain,' 'Nightcrawler,' and 'Prisoners.' With his impressive range and dedication to his craft, Gyllenhaal has established himself as one of the most talented actors of his generation. He consistently delivers compelling performances that showcase his depth and commitment to his characters.",
  },
  {
    id: "pedroPascal",
    name: "Pedro Pascal",
    knownAs: "actor",
    nationality: "Chile",
    bio: "Pedro Pascal is a Chilean-born actor known for his roles in popular TV series such as 'Game of Thrones,' where he portrayed Oberyn Martell, and 'The Mandalorian,' in which he plays the title character. Pascal's charismatic presence and ability to bring his characters to life have garnered him critical acclaim and a dedicated fan following. His talent and versatility continue to shine in his diverse range of performances.",
  },
  {
    id: "bellaRamsey",
    name: "Bella Ramsey",
    knownAs: "actress",
    nationality: "United Kingdom",
    bio: "Bella Ramsey is a British actress known for her breakout role as Lyanna Mormont in the TV series 'Game of Thrones.' Despite her young age, Ramsey has demonstrated incredible talent and a commanding on-screen presence. Her portrayal of strong and resilient characters has earned her praise and recognition, and she continues to impress audiences with her remarkable performances.",
  },
  {
    id: "christopherNolan",
    name: "Christopher Nolan",
    knownAs: "director",
    nationality: "United Kingdom",
    bio: "Christopher Nolan is a British-American film director and screenwriter known for his visionary storytelling and groundbreaking films. With works such as 'Inception,' 'The Dark Knight' trilogy, and 'Interstellar,' Nolan has proven himself to be a master of his craft. His thought-provoking narratives, intricate plot structures, and stunning visuals have captivated audiences worldwide and cemented his status as one of the most influential directors of our time.",
  },
  {
    id: "kilynMorphy",
    name: "Cillian Murphy",
    knownAs: "actor",
    nationality: "Ireland",
    bio: "Cillian Murphy is an Irish actor known for his captivating performances in films such as '28 Days Later,' 'Inception,' and 'Peaky Blinders' (TV series). With his intense and brooding presence, Murphy has consistently delivered compelling portrayals of complex characters. His ability to convey emotions with subtlety and depth has earned him critical acclaim and a loyal fan base.",
  },
  {
    id: "annaTorv",
    name: "Anna Torv",
    knownAs: "actress",
    nationality: "Australia",
    bio: "Anna Torv is an Australian actress known for her roles in TV series such as 'Fringe' and 'Mindhunter.' With her mesmerizing performances and ability to bring depth to her characters, Torv has established herself as a versatile and talented actress. Her dedication to her craft and commitment to delivering nuanced portrayals have earned her recognition and admiration from both critics and audiences.",
  },
  {
    id: "alexanderLud",
    name: "Alexander Ludwig",
    knownAs: "actor",
    nationality: "Canada",
    bio: "Alexander Ludwig is a Canadian actor known for his roles in films such as 'The Hunger Games' and the TV series 'Vikings.' With his striking presence and compelling performances, Ludwig has showcased his range as an actor. He has demonstrated versatility by taking on diverse characters and has proven himself to be a rising talent in the entertainment industry.",
  },
  {
    id: "erinMoriarty",
    name: "Erin Moriarty",
    knownAs: "actress",
    nationality: "United States",
    bio: "Erin Moriarty is an American actress known for her roles in TV series such as 'The Boys' and 'True Detective.' With her natural talent and captivating screen presence, Moriarty has delivered memorable performances that have garnered critical acclaim. She continues to impress audiences with her ability to portray complex and multifaceted characters.",
  },
  {
    id: "dominiqueMcelligott",
    name: "Dominique McElligott",
    knownAs: "actress",
    nationality: "Ireland",
    bio: "Dominique McElligott is an Irish actress known for her roles in TV series such as 'The Boys' and 'Hell on Wheels.' With her remarkable talent and ability to bring depth to her characters, McElligott has captivated audiences and garnered praise for her performances. Her versatility as an actress allows her to seamlessly transition between various genres and portray a wide range of characters.",
  },
  {
    id: "keanuReeves",
    name: "Keanu Reeves",
    knownAs: "actor",
    nationality: "Canada",
    bio: "Keanu Reeves is a Canadian actor known for his roles in iconic films such as 'The Matrix' trilogy, 'John Wick,' and 'Speed.' With his enigmatic presence and charismatic performances, Reeves has become a beloved figure in the entertainment industry. He has demonstrated his versatility as an actor, effortlessly transitioning between action-packed blockbusters and emotionally charged dramas.",
  },
  {
    id: "laurenceFishburne",
    name: "Laurence Fishburne",
    knownAs: "actor",
    nationality: "United States",
    bio: "Laurence Fishburne is an American actor known for his powerful performances in films such as 'The Matrix' trilogy, 'Boyz n the Hood,' and 'The Shawshank Redemption.' With his commanding presence and exceptional acting abilities, Fishburne has become a highly respected figure in the industry. He consistently delivers compelling portrayals and brings depth to his characters.",
  },
  {
    id: "chadStahelsky",
    name: "Chad Stahelski",
    knownAs: "director",
    nationality: "United States",
    bio: "Chad Stahelski is an American film director and stunt coordinator known for his work on the 'John Wick' film series. With his background in stunts, Stahelski has brought a unique and visceral style to the action genre. His expertise in choreographing thrilling fight sequences has earned him recognition and praise from audiences and critics alike.",
  },
  {
    id: "toddPhillips",
    name: "Todd Phillips",
    knownAs: "director",
    nationality: "United States",
    bio: "Todd Phillips is an American film director, producer, and screenwriter known for his work on films such as 'The Hangover' trilogy and 'Joker.' Phillips is celebrated for his ability to blend comedy and drama, creating memorable and impactful films. His distinctive style and storytelling have made him a prominent figure in the industry.",
  },
  {
    id: "joaquinPhoenix",
    name: "Joaquin Phoenix",
    knownAs: "actor",
    nationality: "United States",
    bio: "Joaquin Phoenix is an American actor known for his transformative performances in films such as 'Gladiator,' 'Walk the Line,' and 'Joker.' With his immense talent and dedication to his craft, Phoenix has earned critical acclaim and numerous accolades, including an Academy Award. He fearlessly embraces challenging roles and brings complexity and depth to his characters.",
  },
  {
    id: "mattDamon",
    name: "Matt Damon",
    knownAs: "actor",
    nationality: "United States",
    bio: "Matt Damon is an American actor, producer, and screenwriter known for his roles in films such as 'Good Will Hunting,' the 'Jason Bourne' series, and 'The Martian.' With his charm and versatility, Damon has established himself as one of Hollywood's most recognizable and talented actors. He has proven his ability to captivate audiences with his performances across various genres.",
  },
  {
    id: "anneHathaway",
    name: "Anne Hathaway",
    knownAs: "actress",
    nationality: "United States",
    bio: "Anne Hathaway is an American actress known for her versatile performances in films such as 'Les Misérables,' 'The Devil Wears Prada,' and 'The Dark Knight Rises.' With her exceptional talent and magnetic presence, Hathaway has showcased her ability to portray a wide range of characters. She has received critical acclaim and numerous awards for her compelling portrayals.",
  },
  {
    id: "matthewMcConaughey",
    name: "Matthew McConaughey",
    knownAs: "actor",
    nationality: "United States",
    bio: "Matthew McConaughey is an American actor known for his charismatic performances in films such as 'Dallas Buyers Club,' 'Interstellar,' and 'True Detective' (TV series). With his laid-back charm and remarkable range, McConaughey has captivated audiences and garnered critical acclaim. He has received numerous awards, including an Academy Award, for his compelling portrayals.",
  },
  {
    id: "leonardoDiCaprio",
    name: "Leonardo DiCaprio",
    knownAs: "actor",
    nationality: "United States",
    bio: "Leonardo DiCaprio is an American actor, film producer, and environmental activist. He has portrayed a wide range of characters in films such as 'Titanic,' 'The Departed,' and 'The Revenant.' With his exceptional talent and dedication to his craft, DiCaprio has earned critical acclaim and numerous awards, including an Academy Award. He is known for his commitment to environmental causes and philanthropy.",
  },
  {
    id: "tomHardy",
    name: "Tom Hardy",
    knownAs: "actor",
    nationality: "United Kingdom",
    bio: "Tom Hardy is a British actor known for his transformative performances in films such as 'Inception,' 'Mad Max: Fury Road,' and 'The Revenant.' With his remarkable ability to fully immerse himself in his roles, Hardy has captivated audiences and garnered critical acclaim. He brings intensity and authenticity to his characters, showcasing his versatility as an actor.",
  },
  {
    id: "alvaroMorty",
    name: "Álvaro Morte",
    knownAs: "actor",
    nationality: "Spain",
    bio: "Álvaro Morte is a Spanish actor known for his portrayal of the character Professor in the TV series 'Money Heist.' With his commanding presence and compelling performance, Morte has gained international recognition for his role. He has impressed audiences with his ability to bring depth and complexity to his characters, establishing himself as a prominent figure in the Spanish entertainment industry.",
  },
  {
    id: "pedroAlonso",
    name: "Pedro Alonso",
    knownAs: "actor",
    nationality: "Spain",
    bio: "Pedro Alonso is a Spanish actor known for his role as Berlin in the TV series 'Money Heist.' With his charismatic and enigmatic portrayal, Alonso has garnered praise and adoration from audiences worldwide. He brings a captivating presence to the screen and has become a fan favorite due to his captivating performance and complex characterization.",
  },
  {
    id: "ursulaCorbero",
    name: "Úrsula Corberó",
    knownAs: "actress",
    nationality: "Spain",
    bio: "Úrsula Corberó is a Spanish actress known for her role as Tokyo in the TV series 'Money Heist.' With her dynamic and charismatic performance, Corberó has captivated audiences and gained international recognition. She brings a unique energy to her characters and continues to showcase her talent and versatility in both film and television.",
  },
  {
    id: "harveyGuillen",
    name: "Harvey Guillén",
    knownAs: "actor",
    nationality: "United States",
    bio: "Harvey Guillén is an American actor known for his role as Guillermo de la Cruz in the TV series 'What We Do in the Shadows.' With his comedic timing and relatable portrayal, Guillén has brought laughter to audiences and received critical acclaim for his performance. He continues to impress with his versatility and talent as an actor.",
  },
  {
    id: "antonioBanderas",
    name: "Antonio Banderas",
    knownAs: "actor",
    nationality: "Spain",
    bio: "Antonio Banderas is a Spanish actor, director, and producer known for his roles in films such as 'Desperado,' 'The Mask of Zorro,' and 'Pain and Glory.' With his charismatic presence and exceptional talent, Banderas has become one of the most recognized and respected actors in the industry. He has received critical acclaim for his performances and has been honored with numerous awards.",
  },
  {
    id: "anyaTaylor",
    name: "Anya Taylor-Joy",
    knownAs: "actress",
    nationality: "United States",
    bio: "Anya Taylor-Joy is an American-Argentine-British actress known for her roles in films such as 'The Witch,' 'Split,' and 'Emma.' With her striking appearance and captivating performances, Taylor-Joy has garnered critical acclaim and a dedicated fan base. She brings depth and complexity to her characters, showcasing her versatility and talent as an actress.",
  },
  {
    id: "chrisPratt",
    name: "Chris Pratt",
    knownAs: "actor",
    nationality: "United States",
    bio: "Chris Pratt is an American actor known for his roles in films such as 'Guardians of the Galaxy,' 'Jurassic World,' and 'Parks and Recreation' (TV series). He has become a popular figure in the superhero and blockbuster genres.",
  },
  {
    id: "aaronHorvath",
    name: "Aaron Horvath",
    knownAs: "producer",
    nationality: "United States",
    bio: "Aaron Horvath is an American producer known for his work on the animated TV series 'Teen Titans Go!' He has been involved in the production of numerous episodes and has contributed to the success of the show.",
  },
  {
    id: "kantemirBalagov",
    name: "Kantemir Balagov",
    knownAs: "director",
    nationality: "Russia",
    bio: "Kantemir Balagov is a Russian film director known for his work on the films 'Closeness' and 'Beanpole.' He has gained critical acclaim for his unique storytelling and visual style.",
  },
  {
    id: "michaelJelenic",
    name: "Michael Jelenic",
    knownAs: "producer",
    nationality: "United States",
    bio: "Michael Jelenic is an American producer known for his work on animated TV shows such as 'Teen Titans Go!' and 'Batman: The Brave and the Bold.' He has played a significant role in the development and success of these series.",
  },
  {
    id: "alejandroPinaCalafi",
    name: "Álex Pina",
    knownAs: "producer",
    nationality: "Spain",
    bio: "Álex Pina is a Spanish television producer and writer. He is best known as the creator and showrunner of the TV series 'Money Heist' (La Casa de Papel), which has achieved worldwide success.",
  },
  {
    id: "joelCrawford",
    name: "Joel Crawford",
    knownAs: "director",
    nationality: "United States",
    bio: "Joel Crawford is an American film director known for his work on the animated film 'The Croods: A New Age.' He has contributed to the creative vision and storytelling of the animated feature.",
  },
  {
    id: "lanaWachowski",
    name: "Lana Wachowski",
    knownAs: "director",
    nationality: "United States",
    bio: "Lana Wachowski is an American film director, screenwriter, and producer. She is known for co-creating and directing 'The Matrix' trilogy, as well as other films such as 'Cloud Atlas' and 'Jupiter Ascending.' Wachowski is recognized for her visionary storytelling and groundbreaking visual effects.",
  },
  {
    id: "carrieAnneMoss",
    name: "Carrie-Anne Moss",
    knownAs: "actress",
    nationality: "Canada",
    bio: "Carrie-Anne Moss is a Canadian actress known for her role as Trinity in 'The Matrix' trilogy. She has also appeared in films such as 'Memento' and 'Jessica Jones' (TV series). Moss has established herself as a versatile and talented performer.",
  },
  {
    id: "priyankaChopra",
    name: "Priyanka Chopra",
    knownAs: "actress",
    nationality: "India",
    bio: "Priyanka Chopra is an Indian actress, singer, and film producer. She has starred in numerous Bollywood films and gained international recognition for her role in the TV series 'Quantico.' Chopra has also ventured into music and philanthropy.",
  },
  {
    id: "bryanCranston",
    name: "Bryan Cranston",
    knownAs: "actor",
    nationality: "United States",
    bio: "Bryan Cranston is an American actor known for his iconic role as Walter White in the TV series 'Breaking Bad.' With his exceptional talent and nuanced performances, Cranston has earned critical acclaim and numerous awards. He has showcased his versatility as an actor across various genres, leaving a lasting impact on the industry.",
    image: "",
  },
  {
    id: "aaronPaul",
    name: "Aaron Paul",
    knownAs: "actor",
    nationality: "United States",
    bio: "Aaron Paul is an American actor known for his role as Jesse Pinkman in the TV series 'Breaking Bad.' With his compelling portrayal of a troubled character, Paul has garnered critical acclaim and a dedicated fan base. He continues to deliver powerful performances and has expanded his repertoire in both film and television.",
    image: "",
  },
  {
    id: "bobOdenkirk",
    name: "Bob Odenkirk",
    knownAs: "actor",
    nationality: "United States",
    bio: "Bob Odenkirk is an American actor known for his role as Saul Goodman in the TV series 'Breaking Bad' and its spin-off, 'Better Call Saul.' With his impeccable comedic timing and dramatic range, Odenkirk has impressed audiences and critics alike. He has proven his versatility as an actor and has become a respected figure in the industry.",
    image: "",
  },
  {
    id: "vinceGilligan",
    name: "Vince Gilligan",
    knownAs: "producer",
    nationality: "United States",
    bio: "Vince Gilligan is an American television producer, writer, and director. He is best known as the creator of the TV series 'Breaking Bad' and its prequel, 'Better Call Saul.' Gilligan's visionary storytelling and meticulous attention to detail have made him a prominent figure in the industry. He continues to captivate audiences with his compelling narratives and character development.",
    image: "",
  },
  {
    id: "annaGunn",
    name: "Anna Gunn",
    knownAs: "actress",
    nationality: "United States",
    bio: "Anna Gunn is an American actress known for her role as Skyler White in the TV series 'Breaking Bad.' With her strong performances and ability to portray complex characters, Gunn has garnered critical acclaim. She brings depth and authenticity to her roles, showcasing her talent and making a lasting impact on the screen.",
    image: "",
  },
  {
    id: "erikKripke",
    name: "Eric Kripke",
    knownAs: "producer",
    nationality: "United States",
    bio: "Eric Kripke is an American television writer, producer, and creator of the TV series 'Supernatural,' 'The Boys,' and 'Timeless.' With his creative storytelling and ability to develop captivating narratives, Kripke has garnered a dedicated fan base and critical acclaim. He continues to push boundaries in the industry, delivering innovative and thought-provoking content.",
    image: "",
  },
  {
    id: "evanGoldberg",
    name: "Evan Goldberg",
    knownAs: "producer",
    nationality: "Canada",
    bio: "Evan Goldberg is a Canadian film producer, director, and screenwriter. He is best known for his collaborations with Seth Rogen, including the films 'Superbad,' 'Pineapple Express,' and 'This Is the End.' Goldberg's comedic sensibility and creative vision have made him a prominent figure in the comedy genre. He continues to produce and develop entertaining and successful projects.",
    image: "",
  },
  {
    id: "sethRogen",
    name: "Seth Rogen",
    knownAs: "writer",
    nationality: "Canada",
    bio: "Seth Rogen is a Canadian actor, comedian, writer, and producer. He gained recognition for his roles in comedy films such as 'Superbad,' 'Knocked Up,' and 'Pineapple Express.' With his distinctive laughter and comedic timing, Rogen has become a beloved figure in the entertainment industry. He continues to showcase his talent and versatility across various projects.",
    image: "",
  },
];
